### ISSUE TITLE
learn/_documentation/introducing-learn

### ISSUE THREAD

**Issue by xames3** [xames3/learn#4]
### Discussed in https://github.com/xames3/learn/discussions/3

<div type='discussions-op-text'>

<sup>Originally posted by **utterances-bot** December 23, 2023</sup>
# Let’s L.E.A.R.N! — Home

[https://xames3.github.io/learn/_documentation/introducing-learn.html](https://xames3.github.io/learn/_documentation/introducing-learn.html)</div>

**Comment by xames3** [comment]
~Does this even work?~ Nevermind…

**Comment by kwattorama** [comment]
the project L.E.A.R.N seems well-designed to make AI education more approachable and engaging.
